---

# Notes:
# - This is my cloud config for GCP which doesn't mean it's also suitable for you
# - zone: us-central1-a
# - VM Type mapping. Refer to https://cloud.google.com/compute/docs/machine-types
#   - small:  n1-standard-1	Standard machine type with 1 virtual CPU and 3.75 GB of memory.
#   - small-30g:  samll + 30G HD
#   - medium: n1-standard-2	Standard machine type with 2 virtual CPUs and 7.5 GB of memory.
#   - large:  n1-standard-4	Standard machine type with 4 virtual CPUs and 15 GB of memory.
#   - xlarge: n1-standard-8	Standard machine type with 8 virtual CPUs and 30 GB of memory.
# - Disk Type mapping.
#   - hd5g
#   - hd10g
#   - hd20g
#   - hd30g
#   - hd50g
#   - hd100g
# - Network
#   - network-z1-only
#     * 10.0.100.0/24
#     * reserved: [10.0.100.1-10.0.100.5]
#     * static: [10.0.100.6 - 10.0.100.20]
#   - network-all-azs
#     * 10.0.101.0/24
#     * reserved: [10.0.101.1-10.0.101.5]
#     * static: [10.0.101.6 - 10.0.101.20]
# - Reserved IPs for my components
#   - Vault: 10.0.100.10
#   - Concourse Web: 10.0.100.11
#   - Credhub: 10.0.100.12

# Availability Zones
azs:
- name: z1
  cloud_properties: 
    zone: us-central1-a
- name: z2
  cloud_properties: 
    zone: us-central1-b
- name: z3
  cloud_properties: 
    zone: us-central1-c

# VM Types
vm_types:
- name: small
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
- name: small-30g
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 30
    root_disk_type: pd-ssd
- name: medium
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
- name: large
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
- name: xlarge
  cloud_properties:
    machine_type: n1-standard-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd

# Disk Types
disk_types:
- name: hd5g
  disk_size: 5000
- name: hd10g
  disk_size: 10000
- name: hd20g
  disk_size: 20000
- name: hd30g
  disk_size: 30000
- name: hd50g
  disk_size: 50000
- name: hd100g
  disk_size: 100000

# Networks
# 10.0.100.0/22
# - HostMin:   10.0.100.1            00001010.00000000.011001 00.00000001
# - HostMax:   10.0.103.254          00001010.00000000.011001 11.11111110
networks:
- name: network-z1-only
  type: manual
  subnets:
  - range:   10.0.100.0/24
    gateway: 10.0.100.1
    dns:     [8.8.8.8, 8.8.4.4]
    azs:     [z1]
    reserved: [10.0.100.1-10.0.100.5]
    static: [10.0.100.6 - 10.0.100.20]
    cloud_properties:
      network_name: bosh-sandbox
      subnetwork_name: bosh-releases
      ephemeral_external_ip: true
      tags: [internal, sandbox, bosh-releases]
- name: network-all-azs
  type: manual
  subnets:
  - range:   10.0.101.0/24
    gateway: 10.0.101.1
    dns:     [8.8.8.8, 8.8.4.4]
    azs:     [z1, z2, z3]
    reserved: [10.0.101.1-10.0.101.5]
    static: [10.0.101.6 - 10.0.101.20]
    cloud_properties:
      network_name: bosh-sandbox
      subnetwork_name: bosh-releases
      ephemeral_external_ip: true
      tags: [internal, sandbox, bosh-releases]
- name: eip
  type: vip

# vm_extensions:
# - name: pub-lbs
#   cloud_properties:
#     backend_service: concourse-backend

compilation:
  workers: 2
  reuse_compilation_vms: true
  az: z1
  vm_type: small
  network: network-z1-only